Support plugins with unix socket transport.
lyraproj/hierasdk pull request #3
Opened 2019-12-30 01:07 UTC by flashvoid

This feature introduces support for hiera plugins communicating via unix
sockets. Unix sockets are more secure then tcp sockets listening on
localhost which is important for hiera plugins serving secrets.

This is sdk side of the feature.

2019-12-30 01:17 UTC, flashvoid commented
I'm not very excited about the way plugin configures SDK to use unix socket, my test plugin does this

```
func main() {
	err := os.Setenv("HIERA_PLUGIN_SOCKET", "/tmp/hiera.sock")
	if err != nil {
		panic(err)
	}
	// Register the data_hash function with the global registry
	register.DataHash(`simple-hiera-plugin`, myDataHash)

	// Start RESTful service that makes all registered functions available
	plugin.ServeAndExit()
}
```

more than happy to implement any mechanism that you find more appropriate.

2019-12-30 12:28 UTC, thallgren commented
@flashvoid that sounds interesting indeed. How would you tell Hiera to use a socket? Would it be using a command line option and/or an additional entry in hiera.yaml?

2019-12-30 22:37 UTC, flashvoid commented
This change allows hierasdk to advertise the fact that plugin uses unix socket, supporting change in hiera https://github.com/lyraproj/hiera/pull/59 allows it to extract transport information from plugin metadata and use appropriate connection method.

2020-01-03 11:50 UTC, thallgren commented
Right, but this solution puts the responsibility of selecting transport solely on the plugin and it seems to me like all plugins can benefit from this provided that they run on a system that allows sockets. Thus, the mechanism could be completely built in to the server and the SDK and instead controlled from the server side.

Here's a proposal that I'd like your thoughts on.
1. If the server supports sockets (i.e. not windows), let it advertise this to the client by setting an environment variable.
2. If the client detect that this environment is set, let the SDK create a new temporary socket and then advertise its use (as done in this PR).
3. Optionally, provide an option to control the use of tcp versus sockets (what I mentioned in my previous comment). This might be significant if clients are written in other languages that have no access to the Go SDK but have RESTful tcp stuff built in. Perhaps that deserves a separate PR. I'm just mentioning it because I think the design should allow this to be implemented.

This would make use of sockets the default on systems that provide it.

The solution must ensure that the temporary socket is removed when the plugin terminates.

2020-01-05 07:32 UTC, hbuckle commented
Just a note that newer versions of Windows do [support](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) unix sockets so it would be great if it could work on Windows where supported as well.

2020-01-08 00:03 UTC, flashvoid commented
Switched to using socket directory with semi-randomized socket names instead of having socket names statically defined in plugin config.

2020-01-08 11:50 UTC, thallgren requested changes

2020-01-08 11:50 UTC, thallgren commented on plugin/server.go
> +func tempFile(dir, prefix string) (string, error) {
This isn't safe from a concurrency perspective.
Consider the following:
- Plugin A is started from two different processes simultaneously.
- Both call tempFile before the other has created the actual socket.

This means that both will then make an attempt to use a socket named "\<dir\>/A.socket"

A safer way, which would also avoid the need to use a loop and random numbers, would be to add the process PID to the socket name. I.e.
```
return prefix + "-" + strconv.Itoa(os.Getpid()) + ".socket"
```

2020-01-09 10:11 UTC, thallgren approved these changes

2020-01-09 10:12 UTC, thallgren commented
Merge awaits merge of lyraproj/hiera#59.

2020-01-09 13:25 UTC, merged